### ISSUE TITLE
Switching from email to phone text input field do not change keyboard type and vice-versa

### ISSUE THREAD

**Issue by shazebK** [hackslash-nitp/cura#43]
On a login page in lib/startup_screens/login.dart
There is some problem with UI of the page, when trying to switch from phone number to email section on keeping the keyboard on does not changes the keyboard type, and user is stuck with same numpad keyboard type for writing email address and same is happening from switching email to phone section, user gets stuck with email keyboard type.

![desktop](https://user-images.githubusercontent.com/106864146/195020656-116b792f-90f4-49cb-aec1-b81227913c9d.jpeg)

**Comment by RitwikSingh28** [comment]
That is indeed an issue. I guess what we would have to do is to remove the keyboard focus automatically when the user chooses to change the authentication method.

**Comment by shazebK** [comment]
Yes assign it to me, I was thinking of same solution as told by you.
