### ISSUE TITLE
UI issue in individual homepage

### ISSUE THREAD

**Issue by shazebK** [hackslash-nitp/cura#45]
@RitwikSingh28 
In individual homepage whenever we open a page and close it the font size of homepage content gets smaller,

![WhatsApp Image 2022-10-12 at 12 26 40](https://user-images.githubusercontent.com/106864146/195272274-756cbc41-c261-414a-a248-edd4cc5be465.jpeg)

**Comment by RitwikSingh28** [comment]
It seems like a glitch to me with the ScreenUtil package. I too, am experiencing that some part of the UI's size gets altered when the screen is reloaded.
Any suggestions as to how to solve this issue would be appreciated.

**Comment by RitwikSingh28** [comment]
@shazebK, Would you take on the task to resolve this issue?

**Comment by shazebK** [comment]
Yes I will do it

**Comment by RitwikSingh28** [comment]
Okay then. I am assigning this issue to you.
