### ISSUE TITLE
UI issue, On spend_time page content overflowing.

### ISSUE THREAD

**Issue by shazebK** [hackslash-nitp/cura#47]
On Spend time page content is overflowing when trying to enter the details on that page.
I can solve this issue so I request you to please assign this issue to me.

![WhatsApp Image 2022-10-12 at 18 41 29](https://user-images.githubusercontent.com/106864146/195352852-8a0d0055-6091-4702-bee8-711cd19f6008.jpeg)

**Comment by RitwikSingh28** [comment]
Assigning this issue to you.
