### ISSUE TITLE
Bug in Bottom Navigation Bar

### ISSUE THREAD

**Issue by shazebK** [hackslash-nitp/cura#49]
Current page get pushed on itself on clicking that page icon in Bottom Navigation bar, thus clicking back button does opens up the previous page, this is a bug and need fixing.
I can fix this bug So I request you to assign this issue to me.

https://user-images.githubusercontent.com/106864146/195773640-fe257f6e-4297-4695-92ce-6f72ef39e61d.mp4

**Comment by RitwikSingh28** [comment]
This seems a genuine bug. :thinking:  Please let me know how you are going to fix this bug, before I assign it to you.

**Comment by shazebK** [comment]
I am thinking if ,
In navigation-bar.dart we can check if index of page does not matches with the current page index then only we have to push that page.

**Comment by RitwikSingh28** [comment]
Yes, that seems a plausible fix to me.  Although we also have to consider one scenario, say the user navigates from home to post_feed, then to chat screen, then profile screen, and again clicks on chat_screen. We are pushing new widgets again and again onto the stack, which compromises the performance of the app. I was wondering if we should solve this issue alongside as well, what do you think?

**Comment by shazebK** [comment]
Yes you are right.

**Comment by shazebK** [comment]
What if clicking on back button it directly takes us to homepage only.

**Comment by shazebK** [comment]
Because we already have bottom navigation bar to navigate to required pages,

**Comment by RitwikSingh28** [comment]
Yes, that would be ideal. And when the different icon is clicked, we use pushReplacement to navigate. We will need to take care of the home screen though, because that should not be replaced. For that case, we may use simple push() to put the next page on top of the home-screen

**Comment by RitwikSingh28** [comment]
I guess, we will have to use popUntil() for going back to Home page, when the back button is pressed.

**Comment by shazebK** [comment]
Yeah works fine with me.

**Comment by RitwikSingh28** [comment]
Okay, so with the bug being properly discussed, and an idea formulated, I am assigning this issue to you to resolve.

**Comment by shazebK** [comment]
Ok I will keep these things in mind.

**Comment by RitwikSingh28** [comment]
As per the documentation, popUntil() requires the route name, and since we haven't yet implemented Named Routing in our application, this won't be possible as of now. So, we'll deal with that in an upcoming issue. 
For now, please try to fix the bug the way we had initially discussed.

**Comment by shazebK** [comment]
Yes we can directly push the home page on pressing the back button
