### ISSUE TITLE
Bug : On logging out.

### ISSUE THREAD

**Issue by shazebK** [hackslash-nitp/cura#53]
When we log out of the app, we get back to the login page, here on clicking the back button,crashes the app, I could this fix this issue so I request you to assign it to me.

**Comment by RitwikSingh28** [comment]
Okay.. But before I do that, I would like to ask you how do you propose to solve this issue? :thinking:

**Comment by shazebK** [comment]
I am thinking of completely removing the back button 😅 as after startup screens ,it dont have any good use

**Comment by RitwikSingh28** [comment]
:laughing: That is an interesting fix.... It would work yeah... Okay so, assigning it to you to resolve it.

**Comment by shazebK** [comment]
thanks , i will do my best
