### ISSUE TITLE
Render Overflow in Login Page

### ISSUE THREAD

**Issue by Devank-Sachdeva** [hackslash-nitp/cura#58]
### RenderFlex Overflowed due to the refresh Icon
<img src= "https://user-images.githubusercontent.com/96934308/198088762-f1beea5f-9101-4628-9e3c-808e0b6abd82.png"  width ="500" height = "700"/>

_I would like to try to fix this issue by myself_

**Comment by RitwikSingh28** [comment]
Okay... Assigning it to you. Please resolve this issue within 24 hours.

**Comment by Devank-Sachdeva** [comment]
@RitwikSingh28 Please review https://github.com/hackslash-nitp/cura/pull/61 and provide if any feedback required
