### ISSUE TITLE
PostFeed page - responsive icons layout and routing

### ISSUE THREAD

**Issue by SUSAJJIT** [hackslash-nitp/cura#60]
Issues:-
1.to make icons responsive.
2.to do routing with icons as required .
3.UI modification and minor changes as per design.

**Comment by RitwikSingh28** [comment]
@SUSAJJIT 
Please resolve this issue, and while creating the PR, please include detailed description and screenshots of the UI changes that would be made by the PR. It would help in reviewing the code and making the merging process a lot smoother. :smiley: 

Deadline - **2 days**
