### ISSUE TITLE
Show actual profile information in Info_Page

### ISSUE THREAD

**Issue by RitwikSingh28** [hackslash-nitp/cura#64]
Fetch user-details from the **Firebase Firestore** Database, and display it in the **Info_Page**. :sparkles: 

Following info needs to be linked with backend:
- User DP
- Individual Name, Designation
- Email
- Contact Number
- City
- Country
- About 
- In Drawer, show the User DP and UserName

Anyone interested in working on this, kindly let me know within **2 days** here. We will disucss the procedure and things that you may need to keep in mind while working on this issue. :sunglasses: 

Deadline: **1 day** after having been assigned..

**Comment by shazebK** [comment]
I am interested in doing this task

**Comment by RitwikSingh28** [comment]
Sure.... Assigning it to you :smiley: 
If any query should arise, please let me know here... :thought_balloon:

**Comment by shazebK** [comment]
Thankyou 😊

**Comment by shazebK** [comment]
@RitwikSingh28 
Can you tell me in which file we need to make changes to integrate that page with firebase

**Comment by RitwikSingh28** [comment]
info_page.dart inside lib/individual/

**Comment by shazebK** [comment]
Thanks 👍
