### ISSUE TITLE
Create a create_post Screen

### ISSUE THREAD

**Issue by RitwikSingh28** [hackslash-nitp/cura#75]
**Description**: :thought_balloon: 
> Create a screen that allows the users to create posts. 

**Guidelines**: :bulb: 
> - Create the screen such that it can be accessed by both the Individual and Organization users. 
> - Code should be in a create_post.dart file located in lib/shared/screens folder.
> - Should contain a Textfield to retrieve post_content from user.
> - Allow options to insert multiple pictures/videos/documents, either from the gallery or from camera.
> - A button to share the post.
> - No need to implement Backend transactions in this issue, a separate issue will be created for that later.

**Deadline**: :hourglass_flowing_sand: 
> 4 days after having been assigned.

If interested, please mention it here, so that we may assign it to you.

**Comment by RitwikSingh28** [comment]
Since we don't have a design file specific to the Cura project, I have thought to create the design inspired by Linkedin app's share_post screen.
If you have any more ideas or inspirations to model the design on, please do let me know... 

Reference:
![LinkedIn_Share_Post](https://user-images.githubusercontent.com/106133014/198863589-0e61f816-1c43-4afa-a68a-ffc2745ee082.jpeg)

**Comment by shazebK** [comment]
@RitwikSingh28 
I am interested in taking up this issue can you please clarify -
Do we have to create just the UI of the page or also implement functionality of all the buttons?
Are we open to some custom changes and creativity

**Comment by RitwikSingh28** [comment]
@shazebK Yes, we have to implement functionality of all the buttons. Would be better to split the entire task into different commits, one commit for UI, another for implementing functionalities of the buttons.
Also, yes we are open to making changes as long as it works and aesthetically pleasing.
The backend functionality will be implemented in a separate issue.

**Comment by RitwikSingh28** [comment]
Should I assign this issue to you, @shazebK ?

**Comment by shazebK** [comment]
Yes assign this to me. 
I will try my best to get this task done 😊
